### ISSUE TITLE
Update the What is the Creality Wi-Fi Box? spot

### ISSUE THREAD

**Issue by Hacker1254** [ihrapsa/KlipperWrt#23]
"A router box device released by Creality meant to add network control to your printer.
Big claims, lots of problems and frustrations. No desktop control, only mobile.
No custom slicing only cloud based. No camera support, only claims."

it has a cura plugin, so deaktop printing, it has a camera but only can buy in a kit, the app has had a rework and is much better
still needs a few fixes but it is much better

https://share.crealitycloud.com/creality-cloud/share-content/3362

**Comment by ihrapsa** [comment]
Yeah I know it improved. Will update the info. Thanks!

**Comment by Hacker1254** [comment]
Thank you Sir
