### ISSUE TITLE
I hope to have an image package running openwrt on X86

### ISSUE THREAD

**Issue by BigFlowerFlower** [ihrapsa/KlipperWrt#24]
I hope to have an image package running openwrt on X86

**Comment by ihrapsa** [comment]
Hey, what image package are you talking about?

**Comment by BigFlowerFlower** [comment]
Thank you very much for answering my question. I'm a novice computer. I want to know how klipperwrt runs on X86 based openwrt

**Comment by BigFlowerFlower** [comment]
I use the Microsoft d2550 processor

**Comment by BigFlowerFlower** [comment]
I use it as a soft route

**Comment by ihrapsa** [comment]
Wouldn't be easier to get Debian on it and install Klipper +fluidd/mainsail with [kiauh](https://github.com/th33xitus/kiauh)? Any reason you would prefer OpenWrt on it?
