### ISSUE TITLE
Ender3 Upgrade to Klipper

### ISSUE THREAD

**Issue by spcasey6907** [ihrapsa/KlipperWrt#30]
I have a Creality WIFi Box and have configured with Klipper/Fluidd and appears to be operational, with add digital camera which also works.
Where I am a little scared is the next step creating a 'Printer.cfg' file for the upgrade of the printer's board to klipper. I have read many pages which scare me because you lose control from the attached display to the printer.
Is this true??
How do you tell if my version of the Ender3 will loose control of onboard display?
I am not ready nor was I aware that this was an issue until I got down the rabbit hole.
As I IT Professional I have learned to listen to my instincts....

**Comment by ihrapsa** [comment]
> 
If your display is a serial one (like thoe wone from ender 3 V2) it will not work. That display has it's own mcu and can't be controlled by klipper yet. If you've got the classic display it will work with klipper.

**Comment by spcasey6907** [comment]
Mine connects via ribbon cable to printer board?!?
Is this what you are saying??

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ihrapsa** [comment]
All displays connect via ribbon cable... Do you even know what printer and mainboard you have?

**Comment by XoBoR** [comment]
What he is saying is that TFT displays that have a build in mcu aren't working with klipper, what works is the reprap 12864 style displays, which a lot of creality printers have.

**Comment by spcasey6907** [comment]
[Image.jpeg][Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ihrapsa** [comment]
> 

You haven't uploaded anything

**Comment by spcasey6907** [comment]
[Image.jpeg][Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ihrapsa** [comment]
Still nothing
