### ISSUE TITLE
http://openwrt.local not working

### ISSUE THREAD

**Issue by BEprints** [ihrapsa/KlipperWrt#38]
I have gone though the entire install process and now can not get access I went with the mainsail option and I have also changed the host name to KlipperWrtMax as I am using two 1 for a ender3v2 and 1 for a max.

I've tried http://openwrt.local http://openwrt.local:81 http://box-ip http://box-ip:81 http://KlipperWrtMax.local http://KlipperWrtMax.local:81 http://klipper.local http://klipper.local:81 http://mainsail.local http://mainsail.local:81

Nothing seems to work apart from LuCI though my networks assigned IP address for the box.

**Comment by ihrapsa** [comment]
Hi, if you can't access the box through its ip assigned by the router then something has failed during installation (most likely moonraker). What error do you see when accessing `http://box-ip`?

**Comment by BEprints** [comment]
I cant even access http://box-ip it comes up with This site can’t be reached. would it be worth formatting the SD card and trying install again?

**Comment by ihrapsa** [comment]
Unplug the sd card with the box off, power on the box then plug the sd card back in after the box finishes booting. After that you can try starting over with the two scripts. First one will take care of the formatting and extroot then the second will install the dependencies and klipper/moonraker

**Comment by BEprints** [comment]
I did that and went though the process again and did everything the same as last time. I managed to get it to open mainsail with http://klipperwrtmax.local and it was working fine I then went to find a config file for a Ender 3 Max with CR Touch and now I cant get back into it using http:/klipperwrtmax.local

**Comment by BEprints** [comment]
![Screenshot (18)](https://user-images.githubusercontent.com/115055399/200783347-3995b766-0ad6-408f-9178-7be8f1893944.png)
![Screenshot (7)](https://user-images.githubusercontent.com/115055399/200783358-aaf65365-e638-4d3d-b426-dddf262dd369.png)
![Screenshot (8)](https://user-images.githubusercontent.com/115055399/200783365-47002e21-292c-4e69-9adb-b1c04981940a.png)
![Screenshot (9)](https://user-images.githubusercontent.com/115055399/200783375-d49a770e-e4ec-460d-997e-21d792fe7959.png)
![Screenshot (10)](https://user-images.githubusercontent.com/115055399/200783383-0092c3eb-ca7e-4141-80e7-5e22896eacd8.png)
![Screenshot (11)](https://user-images.githubusercontent.com/115055399/200783388-1f41e81b-09ca-4826-bd8d-f558f796141f.png)
![Screenshot (12)](https://user-images.githubusercontent.com/115055399/200783400-0c5803be-2f5e-458f-8208-b50468372b4b.png)
![Screenshot (13)](https://user-images.githubusercontent.com/115055399/200783414-dfb63f2f-3201-4998-8bf8-b8d7792f641e.png)
![Screenshot (14)](https://user-images.githubusercontent.com/115055399/200783422-28a72845-515f-4021-b7d4-06ffa6e8f16f.png)
![Screenshot (15)](https://user-images.githubusercontent.com/115055399/200783430-42ce6c6b-8bad-44bb-a9e4-0e6f5beddfc4.png)
![Screenshot (16)](https://user-images.githubusercontent.com/115055399/200783436-88397145-d0e4-4749-94d9-abaf65049e9b.png)
![Screenshot (17)](https://user-images.githubusercontent.com/115055399/200783451-6585c7bf-6462-41e7-a6e8-6b9cd474afb9.png)

**Comment by ihrapsa** [comment]
By `http://box-ip` i mean the actual ip of the box your router assigned, not the words. Replace `box-ip` with the actual ip

**Comment by BEprints** [comment]
Oh okay I got you now that's that last photo I can access LuCI with 192.168.1.11:81 but not mainsail

**Comment by ihrapsa** [comment]
Did you try the IP without the `81` port? Also, did you change the static lan IP tona different subnet?

**Comment by BEprints** [comment]
Just using the IP got me in, I don't think I set a static IP I just followed the instructions and the only thing I did different was change the host name and set a password, I tried to change the SSID name but it wont let me it always times out when I apply and save. 

![Screenshot (19)](https://user-images.githubusercontent.com/115055399/200792068-a647e820-65ea-4953-bcf5-1b87bd2c5e69.png)

**Comment by ihrapsa** [comment]
The lan static IP in the box network settings, not in router. Could you check it for me?

**Comment by BEprints** [comment]
I'll check when I stop having problems I can't access though home network now only the boxes wifi

**Comment by BEprints** [comment]
I really don't know what's going on it connects though http://klippermax.local http://klippermax.local:81 when connected to the boxes wifi then when I try it on my home network it doesn't but sometimes it will connect though the IP the router has assigned it 192.168.1.11 192.168.1.11:81 
![Screenshot (23)](https://user-images.githubusercontent.com/115055399/200815503-5eaf5b30-6613-4ba7-ad4a-dbfcdff4e00f.png)
![Screenshot (24)](https://user-images.githubusercontent.com/115055399/200815530-af6d611c-3afc-4bae-af1c-06d132f01ac2.png)
![Screenshot (25)](https://user-images.githubusercontent.com/115055399/200815552-0eedaa69-4ad6-48dd-b57c-324ac2be9677.png)
![Screenshot (26)](https://user-images.githubusercontent.com/115055399/200815589-ecd8aed3-d099-40fa-a194-fe3db28c339e.png)
![Screenshot (27)](https://user-images.githubusercontent.com/115055399/200815641-f093edcc-a7d0-4725-b362-45e954b89c1b.png)
![Screenshot (28)](https://user-images.githubusercontent.com/115055399/200815820-e7e023ad-e716-410f-a0e3-6ca6d424a76a.png)
![Screenshot (29)](https://user-images.githubusercontent.com/115055399/200815857-d31a538b-123d-431a-858b-03c794e1b2bd.png)

**Comment by ihrapsa** [comment]
> No static IP set ![Screenshot (22)](https://user-images.githubusercontent.com/115055399/200813136-00b64ba2-a768-41ee-ba0b-f26ea8e173bb.png)

That's not what I asked for. Go to network - Interfaces - Edit for the lan interface and show the settings there

**Comment by BEprints** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/115055399/200823331-c6fcfc3c-a6ad-46cf-b55a-c90a3dbcc69a.png)

**Comment by BEprints** [comment]
Thank you for your time and help, It is now 0100 hours where I am so I will have a go tomorrrow and start from scratch by going back to the Creality firmware.

**Comment by ihrapsa** [comment]
> ![Screenshot (30)](https://user-images.githubusercontent.com/115055399/200823331-c6fcfc3c-a6ad-46cf-b55a-c90a3dbcc69a.png)

Ok you did change the lan ip subnet to 192.168.2.1 which is fine since ypir router is on 192.168.1.x. However, I'm not sure why you are able to access ot on 192.168.3.1 when connected directly to its hotspot. What did you do there?



> Thank you for your time and help, It is now 0100 hours where I am so I will have a go tomorrrow and start from scratch by going back to the Creality firmware.

You don't need to flash thebstock firmware in order to start from scratch. Just reset the box (hold reset buttom for ~5-6 sec) and  it will revert to fresh openwrt

**Comment by BEprints** [comment]
Hi I originally made it 192.168.2.1 then the second time around I just followed the linked video and just did what he did as to take any potential error on my side that from me choosing my own sub net and changing the host name. That screen shot I had just changed it back to 2.1 to see if it would make any difference.

Okay thanks I'll have a go from fresh openwrt I didn't do that last time I just turned the box off took the sd card out turned on the box and once all light were stable put the sd card back in and ran the 2 scripts.

**Comment by BEprints** [comment]
It might be the wifi in the box playing up as it wouldn't find any networks when scanning and also just randomly disconnected me.
![Screenshot (31)](https://user-images.githubusercontent.com/115055399/201019169-04da6cbe-145a-4cef-94da-6450bafcec91.png)
![Screenshot (32)](https://user-images.githubusercontent.com/115055399/201019188-eb032899-9c98-434e-a57e-e0ec6dbd2efd.png)
![Screenshot (33)](https://user-images.githubusercontent.com/115055399/201019203-de663fbc-459f-484e-8d6d-3a5bfbe7ed38.png)

**Comment by BEprints** [comment]
I've managed to get into mainsail though home network at first it came up say This site can't be reached but then reloaded itself into mainsail
![Screenshot (34)](https://user-images.githubusercontent.com/115055399/201020419-220a70ce-451c-4265-a285-885be4ca9e48.png)

**Comment by BEprints** [comment]
So now it's doing the same thing. I put a printer.cfg file one then came back to make some changes and it said connection to moonraker was lost and to retry, nothing was happing so I unplugged the box and powered it back on this time my router gave it a different IP address to what it was before, yesterday it stayed on 192.168.1.11 and today it was 192.168.1.15 and now is 192.168.1.13 and will only connect though that and not http://klippermax.local

![Screenshot (37)](https://user-images.githubusercontent.com/115055399/201029901-5d1b95ba-1ce9-4f97-8960-26c2bc4275c2.png)
![Screenshot (38)](https://user-images.githubusercontent.com/115055399/201029983-4f45349a-37fa-4203-8645-ede36a612137.png)

**Comment by BEprints** [comment]
Thanks I will give it a go I got off work a bit earlier today so will try some stuff. It has managed to stay with the .13 IP address today but still can't use a .local address to access mainsail

**Comment by BEprints** [comment]
I have reserved 192.168.1.13 for the MAC address of the box in my router

**Comment by BEprints** [comment]
The static IP didn't change anything would only connect though the IP and not the .local I have also tried a reset by holding and without the sd card in I didn't put the sd card back in and the wifi name comes up to what I originally changed it to KipperWrtMax with no password and the IP is back at 3.1 But to get into LuCI I need my password and my home network was already set so I might try go back to original firmware and start again

**Comment by ihrapsa** [comment]
You don't need to go back to stock to start fresh.  If you hold the reset button and your chanfes are srill there then the reset procedure failed. With or without the sd caed plugged hold the reset button until you see the leds flashing. Wait a minute to reboot and everything should return to default (OpenWrt wifi ap, 192.168.1.1 lan ip etc)

If you manage to install everything and reserve the ip we'll look into the avahi daemon that takes care of the hostname.local access

**Comment by BEprints** [comment]
I've held down the rest button for ages the 4th light comes on then second light come on and then they all go out the the process starts over and same result every time. I tried the restore default option that that worked but then when I sent my home network and applied and saved it didn't save and now the boxes wifi doesn't show up so I am going to try get in with a cable.

**Comment by ihrapsa** [comment]
Your box is not reseting. You don't have to hold it for ages, just until it reboots

> I tried the restore default option that that worked

What do you mean by that?

**Comment by BEprints** [comment]
Ethernet cable worked so I am guessing my rest button isn't working properly

**Comment by BEprints** [comment]
I restored back to defaults and have set everything and now it won't show in my home network I will get some screen shots of all my settings I will just need to block out some MAC addresses I really don't know what I am doing wrong.

**Comment by ihrapsa** [comment]
> I restored back to defaults and have set everything

What do you mean by that? did you do it manually or?

**Comment by BEprints** [comment]
> 

I looked into LuCI and used the option under back up/firmware to restore default as the rest button wasn't doing anything just a power cycle well that's all I think it was doing.

**Comment by BEprints** [comment]
I might just have a rubbish box it is Chinese after all, I have a second one I can try I am just away for work at the moment and the second one is at home

**Comment by ihrapsa** [comment]
If you want tor reset it without the button, do a sysupgrade from luci. Upload then upgrade with the `sysupgrade.bin`
![image](https://user-images.githubusercontent.com/40600040/201291999-9063180d-dcc2-4be0-ae13-e28f0105cac1.png)
Make sure to uncheck the. `Keep settings` option

![image](https://user-images.githubusercontent.com/40600040/201292389-9169fbdc-0ad8-4a64-b5ec-c1ba4040fe12.png)

**Comment by BEprints** [comment]
Okay I'll try that

**Comment by BEprints** [comment]
That seems to be working for now, I did the sysupdgrade then unplugged the box removed the sd card and reformatted it I then proceeded with maxing all the changes on the box, host name, passwords, ssid name, home network and terminal I then installed the sd card and ran the scrips all seems to be good at the moment so I will try and access from my phone and save the page to screen and see if that will work reliably.

**Comment by ihrapsa** [comment]
If you plan to access the ui from phone with the `hostname.local` it will most likely not work. It's an android limitation afaik as it defaults to google's DNS. This might have changed recently according to [this](https://source.android.com/docs/core/architecture/modular-system/dns-resolver#mdns-local-resolution) but haven't tested it yet. A more stable setup would be to reserve the ip in router then create the chrome web app shortcut on homescreen. On desktop that should not be an issue

**Comment by BEprints** [comment]
Thanks, on the phone it is only accessible though box.ip but is working fine on my pc and I was able to create a app on pc and it's been consistently connecting though hostname.local

I find it interesting how the box changed to a different host name without the sd card in so maybe there was some conflicting information as I changed the host name a few times trying to get it to work.

**Comment by ihrapsa** [comment]
> I find it interesting how the box changed to a different host name without the sd card in

If you changed the hostname after you setup extroot then those setttings remain on the sd card. If you remove sd card only the settings that were changed on the internal NOR chip apply.

I'm glad you fixed your issues
